fourapp/urls.py
from django.urls import path
from fourapp import views


app_name = 'fourapp'

urlpatterns = [
    path('', views.index, name='index'), #index
    path('new_post/', views.new_post, name='new_post'), #no hay nada en el url, se usa para crear un nuevo post
    path('image/<int:image_id>', views.image, name='image'), #no hay nada en el url, se usa para mostrar una imagen
    path('view_category/<int:category_id>', views.view_category_by_id, name='view_category'), #ver la categoría por id {/view_category/1}
    path('<str:short>', views.view_category_by_short, name='view_category'), #ver la categoría por short {/sci}
    path('post/<int:post_id>', views.view_post, name='view_post'), #ver el post por id {/post/1}
    path('post/<int:post_id>/reply', views.reply, name='reply'), #crear una respuesta al post {/post/1/reply}
    path('<str:short>/post', views.post_from_category, name='post_from_category'), #crear un post directamente desde dentro de la categoria {/sci/post}
    path('edit/<int:post_id>', views.edit_post, name='edit_post'), #editar un post {/edit/1}
    path('delete/<int:post_id>', views.delete_post, name='delete_post'), #eliminar un post {/delete/1}
    path('about/', views.AboutView.as_view(), name='about'), #about {/about}
    path('search/', views.search, name='search'), #buscar un post {/search}
]

fourjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'fourjango'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('fourapp.urls')), #incluyo las urls de fourapp para manejar todo desde la app en lugar de usar el root
    path('users/', include('fourusers.urls')), #incluyo las urls de fourusers para manejar todo desde la app en lugar de usar el root
    path('users/', include('django.contrib.auth.urls')), #incluyo las urls de django para manejar todo desde la app en lugar de usar el root

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #esto lo saqué de un video de codemy

fourusers/urls.py
from django.urls import path
from . import views

app_name = 'fourusers'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/<int:pk>', views.ProfilePage.as_view(), name='profile'),
    path('settings/', views.settings, name='settings'),
]

fourapp/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

#Modelo de las categorías según las cuales se filtran
#lost posts
class Category(models.Model):
    categoryid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)
    short = models.CharField(max_length=3, null=False, default='aaa', unique=True)
    description = models.TextField(null=True)
    nsfw = models.BooleanField(default=False)
    def __str__(self):
        return self.name

#modelo de los posts
class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255, null=False, blank=False, default='anon')
    registereduser = models.ForeignKey('auth.User', related_name='posts', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255, null=False)
    #content = models.TextField(null=False, blank=False)
    content = RichTextField(null=False, blank=False)
    image = models.ImageField(upload_to='postimgs/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    edited = models.BooleanField(default=False)
    viewcounter = models.IntegerField(default=0)
    post_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        print(self.title, self.content, self.image, self.category, self.edited)

class Reply(models.Model):
    reply_id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    username = models.CharField(max_length=255, null=False, blank=False, default='anon')
    registereduser = models.ForeignKey('auth.User', related_name='replies', on_delete=models.CASCADE, null=True)
    content = models.TextField(null=False, blank=False)
    image = models.ImageField(upload_to='replyimgs/', null=True, blank=True)
    edited = models.BooleanField(default=False)
    reply_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.content

fourapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User

class PostFormIndex(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['username', 'title', 'content', 'image', 'category']

class PostFormCategory(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['username', 'title', 'content', 'image']

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class EditUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class EditPasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

fourapp/views.py
from django.shortcuts import redirect, render
from .models import Category, Post, Reply
from .forms import PostFormIndex, PostFormCategory
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from fourusers.models import Profile


def index(request):
    form = PostFormIndex()
    pagetitle = '4jango - Home'
    categories = Category.objects.all()
    context = {'categories': categories, 'pagetitle': pagetitle, 'form': form}
    if not Category.objects.filter(categoryid=1).exists():
        Category.objects.create(categoryid=1, name='General', short='gen', description='General discussion', nsfw=False)
    if request.user.is_authenticated:
        if not Profile.objects.filter(user=request.user).exists():
            Profile.objects.create(user=request.user, name=request.user.username)
    return render(request, 'index.html', context)


def image(request, image_id):
    image = Post.objects.get(post_id=image_id)
    pagetitle = f'4jango - Image {image_id}'
    return render(request, 'image.html', {'image': image, 'pagetitle': pagetitle}) 

def new_post(request):
    if request.method == 'POST':
        username = request.POST['username']
        title = request.POST['title']
        content = request.POST['content']
        category = request.POST.get('category')
        try:
            image = request.FILES['image']
            print(f'{image}')
        except:
            image = None
            print(f'imagen mala fea caca')
        if request.user.is_authenticated:
            registered_user = request.user
        else:
            registered_user = None
        post = Post(registereduser=registered_user, username=username, title=title, \
                    content=content, image=image, \
                    category=Category.objects.get(categoryid=category))
        post.save()
        #if request.referrer == 'same-origin'
        #return redirect('/')
        #else:
        #return redirect('fourapp:view_category pk post.category')
        return redirect('/')

def post_from_category(request, short):
    category = Category.objects.get(short=short)
    categories = Category.objects.all()
    pagetitle = f'4jango - New post in {category.name}'
    if request.method == 'POST':
        username = request.POST['username']
        title = request.POST['title']
        content = request.POST['content']
        category = Category.objects.get(short=short)
        try:
            image = request.FILES['image']
            #print('imagen re piola')
            print(f'{image}')
        except Exception as e:
            image = None
            #print('imagen no piola')
            print(e)
        if request.user.is_authenticated:
            registered_user = request.user
        else:
            registered_user = None
        post = Post(registereduser=registered_user, username=username, title=title, \
        content=content, image=image, \
        category=category)
        post.save()
        return redirect(f'/{short}')

def reply(request, post_id):
    if request.method == 'POST':
        username = request.POST['username']
        content = request.POST['content']
        try:
            image = request.FILES['image']
        except:
            image = None
        if request.user.is_authenticated:
            registered_user = request.user
        else:
            registered_user = None
        post = Post.objects.get(post_id=post_id)
        reply = Reply(registereduser=registered_user, username=username, \
                    content=content, image=image, post=post)
        reply.save()
        return redirect(f'/post/{post_id}')

def view_category_by_id(request, category_id):
    form = PostFormCategory()
    category = Category.objects.get(categoryid=category_id)
    categories = Category.objects.all()
    posts = Post.objects.filter(category=category).order_by('-post_id')
    pagetitle = f'4jango - {category.name}'
    context = {'category': category, 'posts': posts, 'categories': categories, 'pagetitle': pagetitle, 'form': form}
    if category.nsfw == True:
        if request.user.is_authenticated:
            return render(request, 'view_category.html', context)
        else:
            return redirect('/login/')
    return render(request, 'view_category.html', context)

def view_category_by_short(request, short):
    form = PostFormCategory()
    category = Category.objects.get(short=short)
    categories = Category.objects.all()
    posts = Post.objects.filter(category=category).order_by('-post_id')
    pagetitle = f'4jango - {category.name}'
    context = {'category': category, 'posts': posts, 'categories': categories, 'pagetitle': pagetitle, 'form': form}
    if category.nsfw == True:
        if request.user.is_authenticated:
            return render(request, 'view_category.html', context)
        else:
            return redirect('/login/')
    else:
        return render(request, 'view_category.html', context)

def view_post(request, post_id):
    pagetitle = f'4jango - Post #{post_id}'
    categories = Category.objects.all()
    category = Post.objects.get(post_id=post_id).category
    post = Post.objects.get(post_id=post_id)
    replies = Reply.objects.filter(post=post).order_by('-reply_id')
    replycounter = Reply.objects.filter(post_id=post_id).count()
    post.viewcounter = post.viewcounter + 1
    post.save()
    if request.user == post.registereduser:
        editable = True
        deletable = True
    else:
        editable = False
        deletable = False

    context = {'post': post, 'replies': replies, 'category': category, 'categories': categories, 'replycounter': replycounter, 'editable': editable, 'deletable': deletable, 'pagetitle': pagetitle}
    return render(request, 'view_post.html', context)

@login_required(login_url='/users/login/')
def edit_post(request, post_id):
    post = Post.objects.get(post_id=post_id)
    categories = Category.objects.all()
    pagetitle = f'4jango - Edit post #{post_id}'
    context = {'post': post, 'categories': categories, 'pagetitle': pagetitle}
    if request.method == 'POST':
        if post.registereduser == request.user:
            post.title = request.POST['title']
            post.content = request.POST['content']
            try:
                post.image = request.FILES['image']
            except:
                post.image = None
            post.edited = True
            post.save()
            return redirect(f'/post/{post_id}')
        else:
            messages.error(request, 'You are not the owner of this post')
            return redirect(f'/post/{post_id}')
    else:
        return render(request, 'edit_post.html', context)

@login_required(login_url='/users/login/')
def delete_post(request, post_id):
    categories = Category.objects.all()
    post = Post.objects.get(post_id=post_id)
    replies = Reply.objects.filter(post=post)
    pagetitle = f'4jango - Delete post #{post_id}'
    context = {'post': post, 'replies': replies, 'pagetitle': pagetitle, 'categories': categories}
    if request.method == 'POST':
        if post.registereduser == request.user:
            replies.delete()
            post.delete()
            return redirect('/')
        else:
            messages.error(request, 'You are not the owner of this post')
            return redirect(f'/post/{post_id}')
    else:
        return render(request, 'delete_post.html', context)

class AboutView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['pagetitle'] = '4jango - About'
        return context
    template_name = 'about.html'    

def search(request):
    categories = Category.objects.all()
    pagetitle = '4jango - Search'
    context = {'categories': categories, 'pagetitle': pagetitle}
    if request.method == 'GET':
        return render(request, 'search.html', context)
    else:
        search_query = request.POST['search_query']
        titles = Post.objects.filter(title__icontains=search_query)
        contents = Post.objects.filter(content__icontains=search_query)
        usernames = Post.objects.filter(username__icontains=search_query)
        posts = titles | contents | usernames
        context = {'categories': categories, 'pagetitle': pagetitle, 'posts': posts}
        return render(request, 'search.html', context)

fourapp/templates/about.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <div class="aboutUs">

        <h3> 4jango - A django powered 4chan style website. </h3>
        <p> Python course number 31085, Coderhouse.</p>
        <p> Team members: <b>Ignacio Munoz</b>, Jeronimo Coelho, Ignacio Caputo.</p>
        <p> Designed by and developed by: <b>Ignacio Munoz</b></p>

    </div>
{% endblock %}

fourapp/templates/delete_post.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <div class="center-screen">
        <img src="{% static 'images/4jango.png' %}" alt="logo" class="logo" width="9%" height="9%">
        <h1 class="categoryTitle">{{ category.short }} - {{ category.name }}</h1>
    </div>

    <div class="postContainer">
        <table class="postTable">
            <tr>
                <td class="postTableTitle">
                    <a href="/post/{{ post.post_id }}" target="_blank"><h2>{{ post.title }}</h2></a>
                </td>
                {% if editable %}
                <tr>
                    <td class="postTableEdit">
                    <a href="/edit/{{ post.post_id }}">Edit</a>
                    </td>
                {% endif %}
                </tr>
            </tr>
            <tr>
                <td class="postTableDetails"><p><small>#{{ post.post_id }}</small></p></td>
                <td class="postTableDetails"><p><small>{{ post.post_date }}</small></p></td>
                <td class="postTableDetails"><p><small>{{ post.viewcounter }} Views</small></p></td>
                <td class="postTableDetails"><p><small>{{ replycounter }} Replies</small></p></td>
            </tr>
            {% if post.edited %}
            <tr>
                <td class="postTableDetails"><p><small>Edited</small></p></td>
            {% endif %}
            <tr>
                <td class="postTableUser"><h4>{{ post.username }} </h4></td>
            </tr>
            <tr>
                <td class="postTableContent"><p>{{ post.content|safe }}</p></td>
                {% if post.image %}
                <td class="postTableImage"><a href="../media/{{ post.image }}" target="_blank"><img style="width:20%; height:20%" src="../media/{{ post.image }}" loading="lazy"></a></td>
                {% endif %}
            </tr>
        </table>
    </div>

    <div class="postDeletion">
        <p class="dangerZone"> Are you ABSOLUTELY sure you want to delete this post? THIS ACTION CAN NOT BE UNDONE!!!!</p>
        <form action="/delete/{{ post.post_id }}" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes, delete.">
        </form>
    </div>
</body>
{% endblock %}

fourapp/templates/edit_post.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <div class="center-screen categoryTitle">
        <img src="{% static 'images/4jango.png' %}" alt="logo" class="logo" width="9%" height="9%">
        <h1>{{ category.short }} - {{ category.name }}</h1>
    </div>

    <div class="newPostForm center-screen">
        <form class="form-group" action="/edit/{{ post.post_id }}" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <textarea class="textInput" name="title" rows="1" cols="40" placeholder="{{ post.title }}" maxlength="40"></textarea><br>
            <textarea class="textInput" name="content" rows="5" cols="40" placeholder="{{ post.content }}"></textarea><br>
            <input class="form-control-file"type="file" name="image" placeholder="image" accept="image/*"><br>       
            <input type="submit" value="Submit"><br>
        </form>
    </div>
{% endblock %}

fourapp/templates/index.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <br>
    <div class="center-screen">
        <img src="{% static 'images/4jango.png' %}" alt="logo" class="logo" width="13%" height="13%">
    </div>
    <br>

    <div class="newPostForm center-screen">
        <form action="{% url 'fourapp:new_post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p}}
            <input type="submit" value="New Post">
        </form>
    </div>

    <div>
        <h3 class="boardsTitle center-screen">Boards</h3>
        <table class="listCategories center-screen">
            {% if categories %}
                {% for category in categories %}
                <tr>
                    <td class="listCategoriesFullNameTD"><a href="/{{category.short}}">{{ category.name }}</a></td>
                </tr>
                {% endfor %}
            {% else %}
                <p>No categories are available.</p>
            {% endif %}
        </table>
    </div>
    

</body>
</html>
{% endblock %}

fourapp/templates/master.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{{ pagetitle }}</title>
    <link rel="icon" href="{% static 'images/favicon32.ico' %}">
</head>

    {% for message in messages %}
    <div class="alert alert-{{ message.type }}">{{ message.text }}</div>
    {% endfor %}

<body>
    {% block allCategories %}
    <div class="allCategories center-screen">
        {% for entry in categories %}
        <a href="/{{ entry.short }}">[{{ entry.short }}]</a>
        {% endfor %}
    </div>
    {% endblock %}

    {% block siteLinks %}
    <div class="siteLinks">
        <a class="goBack" href="{% url 'fourapp:index' %}">Home</a><br>
        <a class="aboutUs" href="{% url 'fourapp:about' %}">About</a><br>
        <a class="Search" href="{% url 'fourapp:search' %}">Search</a><br>
        {% if user.is_authenticated %}
        <a class="myAccount" href="{% url 'fourusers:profile' request.user.profile.id %}">My profile</a><br>
        <a class="settings" href="{% url 'fourusers:settings' %}">Settings</a><br>
            {% if user.is_superuser %}
            <a href="{% url 'admin:index' %}">Admin Panel</a><br>
            {% endif %}
        <a class="logout" href="{% url 'fourusers:logout' %}">Logout</a><br>
        {% else %}
        <a class="login" href="{% url 'fourusers:login' %}">Login</a><br>
        <a class="register" href="{% url 'fourusers:register' %}">Register</a>
        {% endif %}
    </div>
    {% endblock %}

    {% block content %}
    {% endblock %}

fourapp/templates/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>4jango/Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                {{ form.error }}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[0].placeholder='username';
		form_fields[1].placeholder='password';
		form_fields[2].placeholder='confirm password';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

fourapp/templates/search.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <br>
    <div class="center-screen">
        <img src="{% static 'images/4jango.png' %}" alt="logo" class="logo" width="13%" height="13%">
    </div>

    <h1 class="center-screen">Search for a post by its title, content, or the original poster's username</h1><br>
    <div class="center-screen">
        <form action="{% url 'fourapp:search' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="search_query" placeholder="Search...">
            <input type="submit" value="Search">
        </form>
    </div>
    {% if posts %}
    {% for post in posts %}
    <div class="postContainer">
        <table class="postTable">
            <tr>
                <td class="postTableTitle">
                    <a href="/post/{{ post.post_id }}" target="_blank"><h2>{{ post.title }}</h2></a>
                </td>
            </tr>
            <tr>
                <td class="postTableDetails"><p><small>#{{ post.post_id }}</small></p></td>
                <td class="postTableDetails"><p><small>{{ post.post_date }}</small></p></td>
            </tr>
            <tr>
                <td class="postTableUser"><h4>{{ post.username }} </h4></td>
            </tr>
            <tr>
                <td class="postTableContent"><p>{{ post.content|safe }}</p></td>
                {% if post.image %}
                <td class="postTableImage"><a href="../media/{{ post.image }}" target="_blank"><img style="width:20%; height:20%" src="../media/{{ post.image }}" loading="lazy"></a></td>
                {% endif %}
            </tr>
        </table>
    </div>
    {% endfor %}
    {% else %}
        {% if search_query %}
        <h1 class="center-screen">No results found for '{{ search_query }}'</h1>
        {% endif %}
    {% endif %}
</body>
</html>
{% endblock %}

fourapp/templates/view_category.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <div class="center-screen categoryTitle">
        <img src="{% static 'images/4jango.png' %}" alt="logo" class="logo" width="9%" height="9%">
        <h1>{{ category.short }} - {{ category.name }}</h1>
    </div>
    <br>
    <div class="newPostForm center-screen">
        <form action="{{ category.short }}/post" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p}}
            <input type="hidden" name="category" value="{{ category.categoryid }}">
            <input type="submit" value="New Post">
        </form>
    </div>

    {% for post in posts %}
    <div class="postContainer">
        <table class="postTable">
            <tr>
                <td class="postTableTitle">
                    <a href="/post/{{ post.post_id }}" target="_blank"><h2>{{ post.title }}</h2></a>
                </td>
            </tr>
            <tr>
                <td class="postTableDetails"><p><small>#{{ post.post_id }}</small></p></td>
                <td class="postTableDetails"><p><small>{{ post.post_date }}</small></p></td>
            </tr>
            <tr>
                <td class="postTableUser"><h4>{{ post.username }} </h4></td>
            </tr>
            <tr>
                <td class="postTableContent"><p>{{ post.content|safe }}</p></td>
                {% if post.image %}
                <td class="postTableImage"><a href="../media/{{ post.image }}" target="_blank"><img style="width:20%; height:20%" src="../media/{{ post.image }}" loading="lazy"></a></td>
                {% endif %}
            </tr>
        </table>
    </div>
    {% endfor %}
</body>
</html>
{% endblock %}

fourapp/templates/view_post.html
{% extends 'master.html' %}
{% load static %}
{% block content %}
    <div class="center-screen">
        <img src="{% static 'images/4jango.png' %}" alt="logo" class="logo" width="13%" height="13%">
    </div>
    <div class="center-screen">
        <h1 class="categoryTitle">{{ category.short }} - {{ category.name }}</h1>
    </div>

    <div class="postContainer">
        <table class="postTable">
            <tr>
                <td class="postTableTitle">
                    <h2>{{ post.title }}</h2>
                </td>
                {% if editable %}
                <tr>
                    <td class="postTableEdit">
                    <a href="/edit/{{ post.post_id }}">Edit</a>
                    </td>
                </tr>
                {% endif %}
                {% if deletable %}
                <tr>
                    <td class="postTableDelete">
                    <a href="/delete/{{ post.post_id }}">Delete</a>
                    </td>
                </tr>
                {% endif %}
            </tr>
            <tr>
                <td class="postTableDetails"><p><small>#{{ post.post_id }}</small></p></td>
                <td class="postTableDetails"><p><small>{{ post.post_date }}</small></p></td>
                <td class="postTableDetails"><p><small>{{ post.viewcounter }} Views</small></p></td>
                <td class="postTableDetails"><p><small>{{ replycounter }} Replies</small></p></td>
            </tr>
            {% if post.edited %}
            <tr>
                <td class="postTableDetails"><p><small>Edited</small></p></td>
            {% endif %}
            <tr>
                <td class="postTableUser"><h4>{{ post.username }} </h4></td>
            </tr>
            <tr>
                <td class="postTableContent">{{ post.content|safe }}</td>
                {% if post.image %}
                <td class="postTableImage"><a href="../media/{{ post.image }}" target="_blank"><img style="width:20%; height:20%" src="../media/{{ post.image }}" loading="lazy"></a></td>
                {% endif %}
            </tr>
        </table>
    </div>

    <div class="postReply">
        <h3>Reply</h3>
        <form action="/post/{{ post.post_id }}/reply" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <textarea class="textInput" name="username" rows="1" cols="40" placeholder="username"></textarea><br>
            <textarea class="textInput" name="content" rows="5" cols="40" placeholder="reply"></textarea><br>
            <input class="form-control-file" type="file" name="image" id="image" accept="image/*">
            <input type="submit" value="Reply">
        </form>
    </div>


    <div class="replyContainer">
        <h3>Replies</h3>
        {% if replies %}
        {% for reply in replies %}
        <table class="replyTable">
            <tr>
                <td class="replyTableDetails"><p>{{ reply.username }}</p></td>
                <td class="replyTableDetails"><p>{{ reply.reply_date }}</p></td>
            </tr>
            <tr>
                <td class="replyTableContent"><p>{{ reply.content }}</p></td>
                {% if reply.image %}
                <td class="replyTableContent"><a href="../media/{{ reply.image }}" target="_blank"><img style="width:20%; height:20%" src="../media/{{ reply.image }}"></a></td>
                {% endif %}
            </tr>
        </table>
        {% endfor %}
        {% else %}
        <p><small>There are no replies to this post, yet! Write your own!</small></p>
        {% endif %}
    </div>

</body>
</html>
{% endblock %}